### ISSUE TITLE
Add ScanOptions to kv.Tx scanner interface

### ISSUE THREAD

**Issue by fungl164** [hidal-go/hidalgo#11]
Similar to the tuple store implementations, it would be useful to provide iterator options to those kv backends that could use iterator optimizations (e.g. badger, etc.)
```golang
type ScanOptions struct {
	// KeysOnly is a hint for backend to pre-fetch keys as an optimization for an iterator.
	KeysOnly bool
	// Limit limits the maximal number of key/value pairs to return. Limit <= 0 indicates an unlimited number of results.
	Limit int
	// Prefix is used as a filter for the key scan
	Prefix Key
}

type Scanner interface {
	// Scan iterates over all key-value pairs matching specific parameters.
	Scan(opt *ScanOptions) Iterator
}

// Tx is a transaction over hierarchical key-value store.
type Tx interface {
	base.Tx
	Getter
	// GetBatch fetches values for multiple keys from the database.
	// Nil element in the slice indicates that key does not exists.
	GetBatch(ctx context.Context, keys []Key) ([]Value, error)
	// Put writes a key-value pair to the database.
	// New value will immediately be visible by Get on the same Tx,
	// but implementation might buffer the write until transaction is committed.
	Put(k Key, v Value) error
	// Del removes the key from the database. See Put for consistency guaranties.
	Del(k Key) error
	Scanner
}
```

**Comment by dennwc** [comment]
I see the value of adding those options, but I'm concerned about adding more options, see [comment](https://github.com/hidal-go/hidalgo/issues/12#issuecomment-723889960).

I think we could split those options into two categories: functional and optional. The `Pref`, `Start`, `End` and `Limit` are functional, since changing them will affect the behavior. On the other hand, `KeysOnly` is optional: it's a hint for the backend that values should not be fetched automatically.

So the proposed interface might look like this:

```golang
Scan(r Range, limit int, opt *ScanOptions) Iterator
```

As mentioned on the other issue, it's intentional that all arguments except the options are required and adding more will cause API breakage (new major release).

There is also an possibility to push some of the functional options to the `Iterator` interface, for example:

```golang
// Iterator is the same as before
Scan(r Range) Iterator

type IteratorLimiter interface{
   Iterator
   Limit(n int)
}

func WithLimit(it Iterator, n limit) Iterator {
  if l, ok := it.(IteratorLimiter); ok {
    l.Limit(n)
    return l
  }
  return &limitIterator{it:it, limit:n}
}
```

**Comment by fungl164** [comment]
Thnxs.  Interesting approach and decisions to be made.  Perhaps it may be possible to have a generic interface that you propose with common options such as pref, limit, range, etc. and also have a package-specific ```ScanOptions``` structure for each of the KV implementations used in by hidalgo.  

This would allow developers to choose between generic methods vs speedy/efficient tradeoffs.

Let me know if this makes sense. Thnxs!

**Comment by fungl164** [comment]
After some thought, I came up this. Let me know what you think...

```Go
type Scanner interface {
	// Scan iterates over all key-value pairs matching specific parameters.
	Scan(r Range, opts ...Option) Iterator
}

type Option func(*Iterator)
```
A custom implementation might look like this:
```Go

type iterator struct {
  limit int
  prefix string
  ...
}

func NewCustomStoreIterator(opts ...Option) *iterator {
    it := &iterator{}

    // set the options
    for _, apply := range opts {
        apply(&it)
    }
    ...
    return it
}

func WithLimit(n limit) Option {
  return func(it *Iterator) {
    if l, ok := it.(iterator); ok {
       l.Limit(n)
    }
  }
}

func WithPrefix(prefix string) Option {
  return func(it *Iterator) {
    if l, ok := it.(iterator); ok {
       l.Prefix(prefix)
    }
  }
}

func (it *iterator) Prefix(p string) {
   it.prefix = p
}

func (it *iterator) Limit(n int) {
  it.limit = n
}
```

**Comment by dennwc** [comment]
Yeah, I think it's a reasonable interface to have. It's both simple to implement for naive stores and allows any implementation-specific behaviors.

I assume also:
- `type Option func(*Iterator)` -> `type Option func(Iterator)` (since Iterator is an interface).
- `if !ok { panic("option unsupported") }` to clearly indicate that specific options won't work with those stores.

For the unsupported part, let's also think about `WithLimit` as an example. It's really easy to (inefficiently) implement a limit for a dumb iterator by wrapping it. So I'm wondering if we should allow `Option` to wrap an iterator, if the option is not supported natively?

**Comment by dennwc** [comment]
@fungl164 I ended up with the [following](https://github.com/hidal-go/hidalgo/blob/master/kv/iterator.go#L77):

```go
// IteratorOption is an additional option that affects iterator behaviour.
//
// Implementations in generic KV package should assert for an optimized version of option (via interface assertion),
// and fallback to generic implementation if the store doesn't support this option natively.
type IteratorOption interface {
	// ApplyKV applies option to the KV iterator. Implementation may wrap or replace the iterator.
	ApplyKV(it Iterator) Iterator
}
```

There are no required options (like `Range`), every standard option will have a fallback. The minimal requirement is that the store must be able to scan the whole range and reset iterators to the beginning.

On top of that, there are optional interfaces for iterators like `Seeker` and `PrefixIterator`. If those are implemented they will be used instead of generic callbacks.

This should allow you to make custom options for specific backends, as well as add more generic ones later.
