### ISSUE TITLE
How to Scan over a range (start, end)

### ISSUE THREAD

**Issue by maoueh** [hidal-go/hidalgo#12]
From my current reading of the code, this does not seems possible/implemented. Only scanning using a prefix is possible, or over the full range of keys

Is that correct?

Is this not in there because not enough KV implementation provides it?

**Comment by dennwc** [comment]
Yes, you are right, there is currently no way to iterate over an arbitrary range.

I think almost all backends will be able to run this efficiently. So the only question is how to expose it.

The simplest solution might be to redefine the `Scan`:

```golang
Scan(r Range) Iterator
```

It's possible to make it more generic by accepting some `ScanOpt` as an argument, so we can extend it later. But I think this would be a design mistake: each time a new flag appears all backends will need to be updated, at it will be easy to miss (since the code will still compile).

So I think it's worth cutting a release and make this change as a new major release (maybe with some other changes).

**Comment by dennwc** [comment]
There's now a `kv.Seek` and `flat.Seek` which will help to move the iterator to the right place. Then you can check `it.Key()` until you hit the end of the range.

The required prefix in `Scan` is now replaced with `options.WithPrefix*` and allows more options to be set. So it is possible to specifically define `options.WithRange`, if `Seek`+check is verbose.
